### ISSUE TITLE
Assertion `thtensor' failed.

### ISSUE THREAD

**Issue by oraveczcsaba** [OpenNMT/CTranslate#17]
I might do something very wrong but after a seemingly successful compilation I get this error when I want to start translation simply by
./cli/translate --model model.t7

$ Error: Assertion `thtensor' failed.  at .../CTranslate/src/th/Obj.cc:378

Any quick help would be much appreciated.

**Comment by guillaumekln** [comment]
Could you describe `model.t7`? Is it released with the `release_model.lua` script?

**Comment by oraveczcsaba** [comment]
Oops, my mistake, I forgot to do that... So it is a non-issue, sorry.
