### ISSUE TITLE
How to use with GigaWord Pretrained Text Summarization

### ISSUE THREAD

**Issue by loretoparisi** [OpenNMT/CTranslate#19]
I'm trying to use the text summarization model with `CTranslate`. I'm not sure about how the `GigaWord` corpus was trained (is that using BPE?), so I have tried this way:

```
echo "The quick brown fox jumps over the lazy dog" | ./cli/translate --model /Users/loretoparisi/webservice/textsum_epoch7_14.69_release.t7 --beam_size 5
```

I do not get any output here.

**Comment by guillaumekln** [comment]
Depends on the input I guess. It works fine when using the Giga corpus as input.

**Comment by loretoparisi** [comment]
@guillaumekln Ok, so I'm going to download the training and evaluation data to test it, those available here: https://github.com/harvardnlp/sent-summary, right?

**Comment by guillaumekln** [comment]
Yes.

**Comment by loretoparisi** [comment]
@guillaumekln hey I have to really thank you very much!

```
echo "indian prime minister p.v. narasimha rao 's promise of more autonomy for troubled kashmir and his plea for early state elections has sparked a violent reaction from provincial moslem and opposition parties ." | ./cli/translate --model /Users/loretoparisi/webservice/textsum_epoch7_14.69_release.t7 --beam_size 5
rao 's promise of more autonomy for kashmir
```

This is the first time I'm able to make a text summarization model (pre-trained) working. All the others (`tensorflow`, etc.), despite of all my (and not only) efforts, are too complicated/involes too much data not available/etc. to make it working as a simple testbed!

That's simply great.

**Comment by loretoparisi** [comment]
And funny as well:

```
echo "The club isn't the best place to find a lover So the bar is where I go Me and my friends at the table doing shots Drinking fast" | ./cli/translate --model /Users/loretoparisi/webservice/textsum_epoch7_14.69_release.t7 --beam_size 10
go searching for love
```

👍 

Be serious, what about the training part? The related paper [A Neural Attention Model for Sentence Sum](http://aclweb.org/anthology/D15-1044) does not technically (of course, but sometimes they do) refers to a specific training etc. and I do not see [here](http://opennmt.net/OpenNMT/training/models/) a specific tuturial for text sum.

Thank you.

**Comment by guillaumekln** [comment]
http://forum.opennmt.net/t/text-summarization-on-gigaword-and-rouge-scoring/85

**Comment by loretoparisi** [comment]
Thank you again, closing this.

**Comment by lchunleo** [comment]
may i know how to use the pretrained model for summarization? is there a tutorial on how to do so?

**Comment by guillaumekln** [comment]
Looks like there is everything you need in this thread. What did you try so far?
