### ISSUE TITLE
How to enable cuda support

### ISSUE THREAD

**Issue by StevenLOL** [OpenNMT/CTranslate#2]
Hi, I created a demo project but found that it was unable to load a GPU trained model, would like to give demo that support cuda?

Thanks.

**Comment by guillaumekln** [comment]
As stated in the README, GPU models are not supported (yet). You will need to convert your GPU model to CPU first.

See http://opennmt.net/Advanced/#cpu-translation.

**Comment by StevenLOL** [comment]
Cool , thanks. My original plan is to develop a C++ JsonRPC-OpenNMT server,  then I found that the OpenNMT does have a Lua server.

Thanks again for sharing such a great project!
