### ISSUE TITLE
CTranslate + Tokenizer with case_feature models.

### ISSUE THREAD

**Issue by lpzreq** [OpenNMT/CTranslate#24]
Hello. I have problem with case_feature models.

1) I did model: 
 a) th tokenize with case_feature src and tgt data.
 b) th preprocess with 1000 vocabulary and 10 max sentence length.
 c) th train only with rnn_size 100 and end_epoch 25 (default encoder type and other options).
2) I write my C++ file for using CTranslate library functions.
```
#include <onmt/onmt.h>
std::shared_ptr<name::CTranslator> translator;
//
 int init(const char *model, const char *ptTablePath, int beamSearch) {
    translator = std::make_shared<lingvanex::CTranslator>(model, ptTablePath, beamSearch);
    return 0;
}

int translate(const char *sourceText, char *resultText) {
    char *error(0);
    translator->translate(sourceText, resultText, error); 
    return 0;
}
//
namespace name {
    CTranslator::CTranslator(const char* modelPath, const char* ptTablePath, int beamSearch):
    translator_(onmt::TranslatorFactory::build(modelPath, ptTablePath, true, 1024, beamSearch, false, false)) {}
    
    CTranslator::~CTranslator() {}
    
    int CTranslator::translate(const char *sourceText, char *resultText, char *error) {    
            onmt::ITokenizer* tokenizer = new onmt::Tokenizer(onmt::Tokenizer::Mode::Conservative, "", true, false, false, "");
            std::string result = translator_->translate(sourceText, *tokenizer);
            int resultLength = sizeof(result);
            const char *resultChar = result.c_str();
            int resultCharLength = strlen(resultChar);
            std::cout << sourceText << "\n" << resultChar << std::endl;
            int resultTextLengthBefore = strlen(resultText);
            memcpy(resultText, resultChar, strlen(resultChar));\
            memset(resultText + strlen(resultChar), 0, 2);
            int resultTextLengthAfter = strlen(resultText);
        return 0;
    }
}
```
3) And if i use my model with my code, then i get error.
Assertion failed: (lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"), function Product, file Eigen/src/Core/Product.h, line 97.
4) Error get after program try run this command - rnn_state_enc = _encoder->forward(input); (Translator.hxx 321 line)

Anybody test CTranslate with case_feature? I try test CLI version, but CLI version doesn't have case_feature or tokenization option.

**Comment by guillaumekln** [comment]
Thanks for the detailed report.

It should be fixed with the above commit. If not, feel free to reopen this issue.
