### ISSUE TITLE
Windows 32-bit build fails (TH)

### ISSUE THREAD

**Issue by jhnwnd** [OpenNMT/CTranslate#47]
Specifically, compilation of [THDiskFile.c](https://github.com/OpenNMT/CTranslate/blob/master/lib/TH/THDiskFile.c) fails because int32_t type is undefined. Resolution would be to remove the `#ifdef _WIN64 ` from the include of `<stdint.h>` at the top of the file. This header defines int32_t for standard C, so no `ifdef` is needed.
This was fixed in the main Torch7 repo.
And what do you think of updating TH to the [latest of the Torch7 repo](https://github.com/torch/torch7/tree/master/lib/TH) or better yet to the actively developed C++ version [in ATen](https://github.com/pytorch/pytorch/tree/master/aten/src/TH)? Thanks!

**Comment by guillaumekln** [comment]
The TH dependency is only there to read a serialized Torch model file, so there is little benefits to update if it works. If you care about Windows 32-bit, please send a PR that just fixes this specific issue.
